In [1]:
import pandas as pd

ym = '2019-10'  #统计年月
rate = 6.50899   #当月汇率

path_ch = 'C:/Users/小奔/Desktop/编程练习/Python/数据分析/learnPython/data/ch.csv'
path_jp = 'C:/Users/小奔/Desktop/编程练习/Python/数据分析/learnPython/data/jp.csv'

#导入数据
df_ch = pd.read_csv(path_ch,
                    names=['id','input/output','type','money','datetime','comment','picture']
                    )

df_jp = pd.read_csv(path_jp,
                    names=['id','input/output','type','money','datetime','comment','picture'])

df_ch = df_ch.drop(0)
df_jp = df_jp.drop(0)

In [2]:
#抽出当月的数据

#将数据类型转换为日期类型
df_ch['datetime']= pd.to_datetime(df_ch['datetime'])
df_jp['datetime'] = pd.to_datetime(df_jp['datetime'])

#将日期设为索引
df_ch = df_ch.set_index(['datetime'])
df_jp = df_jp.set_index(['datetime'])

In [3]:
df_ch2 = df_ch[ym]
df_jp2 = df_jp[ym]

df_ch2

,id,input/output,type,money,comment,picture
datetime,,,,,,
2019-10-30 17:57:22,2072434484125277401\t,收入,红包,15.34,NaN,NaN
2019-10-29 16:24:18,2071662866994206253\t,支出,通讯,9.94,NaN,NaN
2019-10-28 20:29:19,2071061415452382104\t,收入,投资,100.22,NaN,NaN
2019-10-28 20:28:34,2071061031530959121\t,支出,家庭基金,100.00,NaN,NaN
2019-10-28 18:52:10,2071012518549951116\t,支出,家居,150.00,开锁,NaN
2019-10-28 12:36:59,2070823676916178005\t,支出,交通,4.00,NaN,NaN
2019-10-28 12:14:57,2070812589718149272\t,支出,用餐,7.30,NaN,NaN
2019-10-28 08:59:19,2070714124799480909\t,收入,投资,388.02,NaN,NaN
2019-10-27 21:15:56,2070360099495255875\t,支出,日用品,8.00,护照夹,NaN
2019-10-27 20:02:25,2070323099182471678\t,支出,交通,15.00,NaN,NaN
2019-10-27 19:58:36,2070321175775321816\t,支出,用餐,46.50,NaN,NaN
2019-10-27 18:13:26,2070268243365239496\t,支出,饮料,20.00,NaN,NaN
2019-10-27 14:31:41,2070156635905365890\t,支出,一般,40.00,NaN,NaN
2019-10-27 12:58:46,2070109869323492394\t,支出,一般,12.20,NaN,NaN
2019-10-27 12:58:41,2070109821667810521\t,支出,用餐,8.10,NaN,NaN
2019-10-26 19:31:31,2069582771886398193\t,支出,日用品,9.90,NaN,NaN
2019-10-26 13:58:20,2069415070316532135\t,支出,用餐,89.00,NaN,NaN
2019-10-25 14:27:52,2068705161170031795\t,支出,食材,96.00,NaN,NaN
2019-10-25 13:39:36,2068680866981125090\t,支出,用餐,8.40,NaN,NaN
2019-10-25 13:11:16,2068666604124541580\t,支出,日用品,7.90,NaN,NaN
2019-10-25 13:10:57,2068666451183443029\t,收入,投资,115.00,NaN,NaN
2019-10-24 16:06:25,2068029985734434627\t,支出,人情,343.82,酒店,NaN
2019-10-24 14:08:07,2067970440718883326\t,支出,食材,44.63,NaN,NaN
2019-10-24 13:08:49,2067940593783185112\t,支出,用餐,9.20,NaN,NaN
2019-10-24 09:16:14,2067823536815119048\t,收入,投资,29.15,NaN,NaN
2019-10-24 01:27:40,2067587701394020226\t,支出,人情,794.15,给曹珍订酒店,NaN
2019-10-23 21:35:27,2067470822784539690\t,支出,日用品,128.50,NaN,NaN
2019-10-23 20:29:53,2067437819886738649\t,支出,用餐,40.00,NaN,NaN
2019-10-23 12:40:46,2067201706131626737\t,支出,通讯,69.00,宽带费,NaN
2019-10-23 12:40:32,2067201585276948903\t,支出,用餐,9.90,NaN,NaN
...,...,...,...,...,...,...
2019-10-19 15:53:28,2064399586420496536\t,支出,娱乐,97.00,温泉,NaN
2019-10-16 10:58:03,2062076578565626568\t,支出,交通,690.00,回国机票,NaN
2019-10-15 21:13:19,2061661472534993962\t,收入,工资,6000.00,佩宝工资,NaN
2019-10-15 20:41:45,2061645587153853657\t,支出,通讯,8.00,NaN,NaN
2019-10-12 09:45:17,2059140844426795761\t,支出,通讯,10.00,NaN,NaN
2019-10-11 17:55:17,2058662695716950439\t,支出,日用品,45.90,NaN,NaN
2019-10-10 19:48:36,2057994954039270442\t,支出,宠物,341.00,NaN,NaN
2019-10-09 05:51:22,2056848788530567921\t,收入,投资,145.10,NaN,NaN
2019-10-09 05:51:10,2056848688563524007\t,收入,投资,521.85,NaN,NaN
2019-10-08 16:42:33,2056451763574053858\t,收入,投资,99.42,NaN,NaN
2019-10-06 06:28:46,2054693279937501058\t,支出,人情,32.00,NaN,NaN
2019-10-06 06:28:38,2054693217635310634\t,支出,交通,65.00,NaN,NaN
2019-10-05 19:21:45,2054357561168010457\t,支出,用餐,10.30,NaN,NaN
2019-10-05 15:10:55,2054231311057328881\t,支出,零食,122.40,NaN,NaN
2019-10-05 11:27:44,2054118981942284711\t,支出,用餐,32.96,NaN,NaN
2019-10-04 21:29:38,2053697154422053016\t,支出,交通,36.00,改签,NaN
2019-10-04 14:32:20,2053487117158224973\t,支出,旅游,60.00,NaN,NaN
2019-10-03 19:52:33,2052923516978633214\t,支出,用餐,30.00,NaN,NaN
2019-10-03 19:27:52,2052911085455843032\t,支出,用餐,25.00,NaN,NaN
2019-10-03 12:24:08,2052697821128071880\t,支出,饮料,2.00,NaN,NaN
2019-10-02 19:49:38,2052197270221133698\t,支出,零食,4.50,NaN,NaN
2019-10-02 12:56:21,2051989258671922218\t,支出,旅游,270.00,NaN,NaN
2019-10-02 06:12:34,2051786024485297369\t,支出,交通,180.00,NaN,NaN
2019-10-02 04:29:16,2051734030315854577\t,支出,用餐,5.00,NaN,NaN
2019-10-01 19:43:45,2051469534083060135\t,支出,用餐,20.00,NaN,NaN
2019-10-01 14:37:45,2051315520792074952\t,支出,交通,4.00,NaN,NaN
2019-10-01 13:29:17,2051281053729855362\t,支出,饮料,20.00,NaN,NaN
2019-10-01 12:10:07,2051241213319617578\t,支出,用餐,149.00,NaN,NaN
2019-10-01 07:05:20,2051087806248164569\t,支出,交通,36.00,NaN,NaN
2019-10-01 06:15:56,2051062942430829297\t,支出,用餐,11.80,NaN,NaN

In [4]:
#转换日元汇率

#df_jp2['money'] = df_jp2['money']*rate/100

df_jp2['money'] = df_jp2['money'].map(lambda x : float(x)*rate/100)
df_jp2['money'] = df_jp2['money'].round(2)

c:\users\小奔\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
c:\users\小奔\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [5]:
df_ch2['money'] = df_ch2['money'].astype('float64')

df_ch2.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 65 entries, 2019-10-30 17:57:22 to 2019-10-01 06:15:56
Data columns (total 6 columns):
id              65 non-null object
input/output    65 non-null object
type            65 non-null object
money           65 non-null float64
comment         11 non-null object
picture         0 non-null object
dtypes: float64(1), object(5)
memory usage: 2.3+ KB

c:\users\小奔\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [6]:
#合并两张表

df_reslut = df_ch2.append(df_jp2)

df_reslut = df_reslut.drop(columns = ['picture','id'])

df_reslut.describe()

             money
count   119.000000
mean    190.798571
std     807.698926
min       1.300000
25%      10.150000
50%      37.750000
75%      98.210000
max    6491.420000

In [7]:
#消费行为统计

cash = df_reslut['money'].groupby(df_reslut['input/output'])

cash.sum()

input/output
支出     8259.85
收入    14445.18
Name: money, dtype: float64

In [8]:
#分组统计，排序

cash_flow = df_reslut.groupby(['input/output','type']).sum()

cash_flow.sort_values(['input/output','money'],ascending = False)

                      money
input/output type
收入           工资    12491.42
             投资     1398.76
             红包      340.79
             一般      152.31
             报销       61.90
支出           交通     2243.51
             用餐     2196.26
             人情     1169.97
             旅游      425.68
             日用品     377.26
             零食      367.08
             宠物      341.00
             丽人      234.32
             娱乐      174.85
             家居      150.00
             食材      140.63
             住房      113.00
             家庭基金    100.00
             通讯       96.94
             一般       71.73
             饮料       57.62

In [9]:
#导出csv文件
path = 'C:/Users/小奔/Desktop/编程练习/Python/数据分析/learnPython/data/'+ ym +'.csv'

cash_flow.to_csv(path,encoding='gbk')